<template>
    <div id="app">
        <bootstrap-data-table @allSelected="allSelected" :general-search="true" v-bind="table"/>
    </div>
</template>

<script>
    import BootstrapDataTable from "./BootstrapDataTable";
    import TestColumn from "./datatable/TestColumn";

    export default {
        name: 'App',
        components: {BootstrapDataTable},
        data() {
            return {
                table: {
                    columns: [{
                        name: '{checkbox}', action() {
                            // console.log(s, d);
                        }
                    }, {name: '{id}'}, {name: 'id', title: 'PIN'}, {name: 'first_name', search: true}, {name: 'last_name', search: true},
                        {name: 'email', search: 'email'}, {name: 'gender', search: ['male', 'female']}, {name: 'ip_address'}, {name: TestColumn},
                        {
                            name: "{view}{edit}{delete}", title: "", action(e, d) {
                                alert('We are here: ' + e + ' for ID: ' + d.id)
                            }
                        }],
                    data: [
                        {
                            "id": 1,
                            "first_name": "Emmaline",
                            "last_name": "Lunt",
                            "email": "elunt0@businesswire.com",
                            "gender": "Female",
                            "ip_address": "71.112.180.100"
                        }, {
                            "id": 2,
                            "first_name": "Elene",
                            "last_name": "Broster",
                            "email": "ebroster1@sciencedaily.com",
                            "gender": "Female",
                            "ip_address": "83.238.98.109"
                        }, {
                            "id": 3,
                            "first_name": "Bart",
                            "last_name": "Frier",
                            "email": "bfrier2@netscape.com",
                            "gender": "Male",
                            "ip_address": "73.117.170.178"
                        }, {
                            "id": 4,
                            "first_name": "Augusto",
                            "last_name": "Holcroft",
                            "email": "aholcroft3@squidoo.com",
                            "gender": "Male",
                            "ip_address": "123.74.170.18"
                        }, {
                            "id": 5,
                            "first_name": "Bucky",
                            "last_name": "Spinozzi",
                            "email": "bspinozzi4@usa.gov",
                            "gender": "Male",
                            "ip_address": "41.33.176.216"
                        }, {
                            "id": 6,
                            "first_name": "Marlie",
                            "last_name": "McGuigan",
                            "email": "mmcguigan5@ezinearticles.com",
                            "gender": "Female",
                            "ip_address": "136.11.193.60"
                        }, {
                            "id": 7,
                            "first_name": "Ruby",
                            "last_name": "Everett",
                            "email": "reverett6@opera.com",
                            "gender": "Female",
                            "ip_address": "41.226.164.144"
                        }, {
                            "id": 8,
                            "first_name": "Stearne",
                            "last_name": "Donovin",
                            "email": "sdonovin7@samsung.com",
                            "gender": "Male",
                            "ip_address": "102.160.21.73"
                        }, {
                            "id": 9,
                            "first_name": "Hamlen",
                            "last_name": "Castanone",
                            "email": "hcastanone8@lulu.com",
                            "gender": "Male",
                            "ip_address": "2.243.254.199"
                        }, {
                            "id": 10,
                            "first_name": "Leroy",
                            "last_name": "Stambridge",
                            "email": "lstambridge9@prlog.org",
                            "gender": "Male",
                            "ip_address": "150.108.133.62"
                        }, {
                            "id": 11,
                            "first_name": "Jameson",
                            "last_name": "Karleman",
                            "email": "jkarlemana@usa.gov",
                            "gender": "Male",
                            "ip_address": "108.125.126.250"
                        }, {
                            "id": 12,
                            "first_name": "Andonis",
                            "last_name": "Guarin",
                            "email": "aguarinb@sciencedirect.com",
                            "gender": "Male",
                            "ip_address": "5.38.209.234"
                        }, {
                            "id": 13,
                            "first_name": "Tierney",
                            "last_name": "Hurll",
                            "email": "thurllc@auda.org.au",
                            "gender": "Female",
                            "ip_address": "190.218.237.38"
                        }, {
                            "id": 14,
                            "first_name": "Winifred",
                            "last_name": "Coysh",
                            "email": "wcoyshd@census.gov",
                            "gender": "Female",
                            "ip_address": "65.204.217.67"
                        }, {
                            "id": 15,
                            "first_name": "Afton",
                            "last_name": "Glencrash",
                            "email": "aglencrashe@va.gov",
                            "gender": "Female",
                            "ip_address": "149.180.43.248"
                        }, {
                            "id": 16,
                            "first_name": "Yale",
                            "last_name": "Vayro",
                            "email": "yvayrof@admin.ch",
                            "gender": "Male",
                            "ip_address": "39.190.35.65"
                        }, {
                            "id": 17,
                            "first_name": "Granger",
                            "last_name": "Kensit",
                            "email": "gkensitg@1und1.de",
                            "gender": "Male",
                            "ip_address": "25.5.231.111"
                        }, {
                            "id": 18,
                            "first_name": "Galvin",
                            "last_name": "Gerner",
                            "email": "ggernerh@nsw.gov.au",
                            "gender": "Male",
                            "ip_address": "163.127.130.55"
                        }, {
                            "id": 19,
                            "first_name": "Nicoline",
                            "last_name": "Tomaello",
                            "email": "ntomaelloi@mediafire.com",
                            "gender": "Female",
                            "ip_address": "60.33.250.40"
                        }, {
                            "id": 20,
                            "first_name": "Aluino",
                            "last_name": "Shimwall",
                            "email": "ashimwallj@yellowpages.com",
                            "gender": "Male",
                            "ip_address": "69.116.101.58"
                        }, {
                            "id": 21,
                            "first_name": "Tessi",
                            "last_name": "Hanby",
                            "email": "thanbyk@wikia.com",
                            "gender": "Female",
                            "ip_address": "241.1.74.61"
                        }, {
                            "id": 22,
                            "first_name": "Tull",
                            "last_name": "Ram",
                            "email": "traml@nbcnews.com",
                            "gender": "Male",
                            "ip_address": "96.125.169.253"
                        }, {
                            "id": 23,
                            "first_name": "Luciano",
                            "last_name": "Toplin",
                            "email": "ltoplinm@baidu.com",
                            "gender": "Male",
                            "ip_address": "198.254.13.154"
                        }, {
                            "id": 24,
                            "first_name": "Mill",
                            "last_name": "Chowne",
                            "email": "mchownen@fc2.com",
                            "gender": "Male",
                            "ip_address": "132.198.119.24"
                        }, {
                            "id": 25,
                            "first_name": "Dasya",
                            "last_name": "Westhead",
                            "email": "dwestheado@usnews.com",
                            "gender": "Female",
                            "ip_address": "189.8.200.193"
                        }, {
                            "id": 26,
                            "first_name": "Bern",
                            "last_name": "Spavins",
                            "email": "bspavinsp@delicious.com",
                            "gender": "Male",
                            "ip_address": "154.20.51.173"
                        }, {
                            "id": 27,
                            "first_name": "Lancelot",
                            "last_name": "Camamile",
                            "email": "lcamamileq@bizjournals.com",
                            "gender": "Male",
                            "ip_address": "19.0.162.44"
                        }, {
                            "id": 28,
                            "first_name": "Nil",
                            "last_name": "D'Emanuele",
                            "email": "ndemanueler@amazon.co.uk",
                            "gender": "Male",
                            "ip_address": "192.18.15.143"
                        }, {
                            "id": 29,
                            "first_name": "Frankie",
                            "last_name": "Sedworth",
                            "email": "fsedworths@miitbeian.gov.cn",
                            "gender": "Male",
                            "ip_address": "125.236.153.105"
                        }, {
                            "id": 30,
                            "first_name": "Knox",
                            "last_name": "Blease",
                            "email": "kbleaset@fc2.com",
                            "gender": "Male",
                            "ip_address": "107.26.141.190"
                        }, {
                            "id": 31,
                            "first_name": "Laurel",
                            "last_name": "Laverenz",
                            "email": "llaverenzu@mapy.cz",
                            "gender": "Female",
                            "ip_address": "104.13.6.52"
                        }, {
                            "id": 32,
                            "first_name": "Ricca",
                            "last_name": "Dufour",
                            "email": "rdufourv@globo.com",
                            "gender": "Female",
                            "ip_address": "42.187.234.201"
                        }, {
                            "id": 33,
                            "first_name": "Tadio",
                            "last_name": "Linde",
                            "email": "tlindew@tinyurl.com",
                            "gender": "Male",
                            "ip_address": "213.74.11.33"
                        }, {
                            "id": 34,
                            "first_name": "Raimondo",
                            "last_name": "Pentland",
                            "email": "rpentlandx@pbs.org",
                            "gender": "Male",
                            "ip_address": "125.90.94.202"
                        }, {
                            "id": 35,
                            "first_name": "Ange",
                            "last_name": "Galier",
                            "email": "agaliery@oaic.gov.au",
                            "gender": "Male",
                            "ip_address": "68.222.131.80"
                        }, {
                            "id": 36,
                            "first_name": "Samara",
                            "last_name": "Pilsworth",
                            "email": "spilsworthz@bbb.org",
                            "gender": "Female",
                            "ip_address": "195.240.231.17"
                        }, {
                            "id": 37,
                            "first_name": "Essie",
                            "last_name": "Decroix",
                            "email": "edecroix10@ucoz.com",
                            "gender": "Female",
                            "ip_address": "97.17.214.0"
                        }, {
                            "id": 38,
                            "first_name": "Blinni",
                            "last_name": "Toffetto",
                            "email": "btoffetto11@hexun.com",
                            "gender": "Female",
                            "ip_address": "88.69.93.240"
                        }, {
                            "id": 39,
                            "first_name": "Maryanne",
                            "last_name": "Salvadore",
                            "email": "msalvadore12@kickstarter.com",
                            "gender": "Female",
                            "ip_address": "134.202.45.170"
                        }, {
                            "id": 40,
                            "first_name": "Binky",
                            "last_name": "Iacovides",
                            "email": "biacovides13@irs.gov",
                            "gender": "Male",
                            "ip_address": "93.190.130.234"
                        }, {
                            "id": 41,
                            "first_name": "Cedric",
                            "last_name": "Aimer",
                            "email": "caimer14@stumbleupon.com",
                            "gender": "Male",
                            "ip_address": "171.53.136.253"
                        }, {
                            "id": 42,
                            "first_name": "Lonnie",
                            "last_name": "Leftly",
                            "email": "lleftly15@cbslocal.com",
                            "gender": "Male",
                            "ip_address": "5.21.83.121"
                        }, {
                            "id": 43,
                            "first_name": "Archibold",
                            "last_name": "Sievewright",
                            "email": "asievewright16@cdbaby.com",
                            "gender": "Male",
                            "ip_address": "168.220.202.54"
                        }, {
                            "id": 44,
                            "first_name": "Kailey",
                            "last_name": "Kitman",
                            "email": "kkitman17@tamu.edu",
                            "gender": "Female",
                            "ip_address": "3.179.117.115"
                        }, {
                            "id": 45,
                            "first_name": "Alisha",
                            "last_name": "Gayden",
                            "email": "agayden18@dot.gov",
                            "gender": "Female",
                            "ip_address": "5.17.147.87"
                        }, {
                            "id": 46,
                            "first_name": "Parry",
                            "last_name": "MacNeachtain",
                            "email": "pmacneachtain19@sitemeter.com",
                            "gender": "Male",
                            "ip_address": "119.240.48.159"
                        }, {
                            "id": 47,
                            "first_name": "Miran",
                            "last_name": "Dandison",
                            "email": "mdandison1a@prlog.org",
                            "gender": "Female",
                            "ip_address": "31.15.136.1"
                        }, {
                            "id": 48,
                            "first_name": "Burt",
                            "last_name": "Humby",
                            "email": "bhumby1b@livejournal.com",
                            "gender": "Male",
                            "ip_address": "199.57.161.101"
                        }, {
                            "id": 49,
                            "first_name": "Bradly",
                            "last_name": "Copozio",
                            "email": "bcopozio1c@npr.org",
                            "gender": "Male",
                            "ip_address": "243.143.181.108"
                        }, {
                            "id": 50,
                            "first_name": "Tarrance",
                            "last_name": "Ritchman",
                            "email": "tritchman1d@salon.com",
                            "gender": "Male",
                            "ip_address": "76.123.232.144"
                        }
                    ]
                }
            };
        }, methods: {
            allSelected(v) {
                console.log(v ? 'All selected' : 'None Selected');
            }
        }
    }
</script>

<style>
    #app {
        font-family: Avenir, Helvetica, Arial, sans-serif;
        -webkit-font-smoothing: antialiased;
        -moz-osx-font-smoothing: grayscale;
        text-align: center;
        color: #2c3e50;
        margin-top: 60px;
    }
</style>
